using System.Globalization;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Text;

namespace VirtualMarina.Docs.ApiDocGen;

/// <summary>Writes the Markdown reference: a table of contents, then one section per type with a table of its members.</summary>
internal sealed class ApiReferenceWriter(XmlDocumentation docs)
{
    private static readonly CultureInfo Invariant = CultureInfo.InvariantCulture;

    private static readonly Dictionary<Type, string> Aliases = new()
    {
        [typeof(void)] = "void",
        [typeof(bool)] = "bool",
        [typeof(byte)] = "byte",
        [typeof(int)] = "int",
        [typeof(uint)] = "uint",
        [typeof(long)] = "long",
        [typeof(float)] = "float",
        [typeof(double)] = "double",
        [typeof(string)] = "string",
        [typeof(object)] = "object",
        [typeof(char)] = "char",
        [typeof(decimal)] = "decimal",
    };

    private static readonly HashSet<string> RecordMethods = ["Equals", "GetHashCode", "ToString", "Deconstruct", "PrintMembers", "<Clone>$"];

    private readonly NullabilityInfoContext _nullability = new();
    private readonly StringBuilder _text = new();
    private Dictionary<Type, string> _anchors = [];

    public string Write(IReadOnlyList<Type> types)
    {
        _anchors = Anchors(types);
        _text.Clear();
        _text.AppendLine("# API reference");
        _text.AppendLine();
        _text.AppendLine("Every public type and member of the VirtualMarina libraries, with the summary from its XML documentation.");
        _text.AppendLine("Generated by `Docs/tools/ApiDocGen` (`dotnet run --project Docs/tools/ApiDocGen -- Docs/11-api-reference.md`); do not edit by hand.");
        _text.AppendLine("Guides with examples are listed in the [documentation index](README.md).");
        _text.AppendLine();

        // Table of contents
        foreach (var group in types.GroupBy(t => t.Namespace))
        {
            _text.AppendLine(Invariant, $"- **{group.Key}**: {string.Join(", ", group.Select(t => $"[{DisplayTypeName(t)}](#{_anchors[t]})"))}");
        }

        _text.AppendLine();

        foreach (var group in types.GroupBy(t => t.Namespace))
        {
            _text.AppendLine(Invariant, $"## {group.Key}");
            _text.AppendLine();
            foreach (var type in group) WriteType(type);
        }

        return _text.ToString();
    }

    /// <summary>
    /// The anchor of each type's heading: its lower-cased name, or, where two namespaces publish a type of the same name
    /// (the Blazor and WinForms MarinaDesignerPanel), its namespace-qualified name, so every link lands on its own type.
    /// </summary>
    private static Dictionary<Type, string> Anchors(IReadOnlyList<Type> types)
    {
        var shared = types.GroupBy(DisplayTypeName, StringComparer.OrdinalIgnoreCase)
            .Where(g => g.Count() > 1)
            .Select(g => g.Key)
            .ToHashSet(StringComparer.OrdinalIgnoreCase);

        return types.ToDictionary(t => t, t => Slug(shared.Contains(DisplayTypeName(t)) ? t.Namespace + "." + DisplayTypeName(t) : DisplayTypeName(t)));

        static string Slug(string name)
        {
#pragma warning disable CA1308 // Anchors are lower-case by the convention Markdown renderers use for heading ids; nothing compares them.
            var lower = name.ToLowerInvariant();
#pragma warning restore CA1308
            return lower
                .Replace("<", "", StringComparison.Ordinal)
                .Replace(">", "", StringComparison.Ordinal)
                .Replace(".", "-", StringComparison.Ordinal)
                .Replace(", ", "-", StringComparison.Ordinal);
        }
    }

    private void WriteType(Type type)
    {
        _text.AppendLine(Invariant, $"<a id=\"{_anchors[type]}\"></a>");
        _text.AppendLine(Invariant, $"### {DisplayTypeName(type)}");
        _text.AppendLine();
        _text.AppendLine(Invariant, $"`{Kind(type)} {DisplayTypeName(type)}{BaseList(type)}`");
        _text.AppendLine();
        var typeDoc = docs.For(type);
        if (typeDoc.Summary.Length > 0) _text.AppendLine(typeDoc.Summary).AppendLine();
        if (typeDoc.Remarks.Length > 0) _text.AppendLine(typeDoc.Remarks).AppendLine();

        if (type.IsEnum)
        {
            _text.AppendLine("| Value | Description |");
            _text.AppendLine("|---|---|");
            foreach (var field in type.GetFields(BindingFlags.Public | BindingFlags.Static))
            {
                var value = Convert.ToInt64(field.GetRawConstantValue(), Invariant);
                _text.AppendLine(Invariant, $"| `{field.Name}` = {value} | {Cell(docs.For(field).Summary)} |");
            }

            _text.AppendLine();
            return;
        }

        var rows = MemberRows(type);
        if (rows.Count > 0)
        {
            _text.AppendLine("| Member | Description |");
            _text.AppendLine("|---|---|");
            foreach (var (signature, summary) in rows) _text.AppendLine(Invariant, $"| `{Code(signature)}` | {Cell(summary)} |");
            _text.AppendLine();
        }
    }

    private List<(string Signature, string Summary)> MemberRows(Type type)
    {
        var rows = new List<(string Signature, string Summary)>();

        foreach (var ctor in type.GetConstructors(DocIds.AllDeclared).Where(IsVisible).Where(c => !IsRecordCopyConstructor(c)))
        {
            var summary = docs.For(ctor).Summary;
            if (summary.Length == 0)
            {
                summary = ctor.GetParameters().Length == 0
                    ? "Creates an instance with default values."
                    : IsRecord(type) ? "Positional constructor; the parameters are described on the properties below." : "";
            }

            rows.Add(($"{Access(ctor)}{DisplayTypeName(type).Split('<')[0]}({Parameters(ctor)})", summary));
        }

        foreach (var field in type.GetFields(DocIds.AllDeclared).Where(f => f.IsPublic || f.IsFamily).Where(f => !f.IsSpecialName))
        {
            var modifier = field.IsLiteral ? "const " : field.IsStatic ? "static readonly " : "";
            var constant = field.IsLiteral ? $" = {FormatValue(field.GetRawConstantValue())}" : "";
            rows.Add(($"{modifier}{TypeName(field.FieldType, _nullability.Create(field))} {field.Name}{constant}", docs.For(field).Summary));
        }

        foreach (var property in type.GetProperties(DocIds.AllDeclared).Where(p => IsVisible(p.GetMethod) || IsVisible(p.SetMethod)))
        {
            if (property.Name == "EqualityContract") continue;
            var accessors = new List<string>();
            if (IsVisible(property.GetMethod)) accessors.Add("get;");
            if (IsVisible(property.SetMethod)) accessors.Add(IsInitOnly(property.SetMethod!) ? "init;" : "set;");
            var isStatic = (property.GetMethod ?? property.SetMethod)!.IsStatic ? "static " : "";
            var indexParameters = property.GetIndexParameters();
            var name = indexParameters.Length > 0
                ? $"this[{string.Join(", ", indexParameters.Select(p => $"{TypeName(p.ParameterType, _nullability.Create(p))} {p.Name}"))}]"
                : property.Name;
            rows.Add(($"{isStatic}{TypeName(property.PropertyType, _nullability.Create(property))} {name} {{ {string.Join(" ", accessors)} }}", docs.For(property).Summary));
        }

        foreach (var ev in type.GetEvents(DocIds.AllDeclared).Where(e => IsVisible(e.AddMethod)))
        {
            rows.Add(($"event {TypeName(ev.EventHandlerType!, _nullability.Create(ev))} {ev.Name}", docs.For(ev).Summary));
        }

        var isComponent = typeof(Microsoft.AspNetCore.Components.ComponentBase).IsAssignableFrom(type);
        foreach (var method in type.GetMethods(DocIds.AllDeclared).Where(IsVisible).Where(m => !m.IsSpecialName).OrderBy(m => m.Name, StringComparer.Ordinal))
        {
            if (IsRecord(type) && RecordMethods.Contains(method.Name)) continue;
            if (isComponent && method.Name == "BuildRenderTree") continue; // Razor-generated
            if (method.Name is "Equals" or "GetHashCode" && method.DeclaringType!.IsValueType) continue;
            var generic = method.IsGenericMethodDefinition ? "<" + string.Join(", ", method.GetGenericArguments().Select(a => a.Name)) + ">" : "";
            var modifiers = (method.IsStatic ? "static " : "") + (method.IsFamily ? "protected " : "") + (IsOverride(method) ? "override " : "");
            var returnType = TypeName(method.ReturnType, _nullability.Create(method.ReturnParameter));
            rows.Add(($"{modifiers}{returnType} {method.Name}{generic}({Parameters(method)})", docs.For(method).Summary));
        }

        return rows;
    }

    private string Parameters(MethodBase method) => string.Join(", ", method.GetParameters().Select(p =>
    {
        var prefix = p.IsOut ? "out " : p.ParameterType.IsByRef ? "ref " : p.IsDefined(typeof(ParamArrayAttribute)) ? "params " : "";
        var type = TypeName(p.ParameterType.IsByRef ? p.ParameterType.GetElementType()! : p.ParameterType, _nullability.Create(p));
        var defaultValue = p.HasDefaultValue ? " = " + FormatValue(p.RawDefaultValue, p.ParameterType) : "";
        return $"{prefix}{type} {p.Name}{defaultValue}";
    }));

    // ---- Formatting helpers ---------------------------------------------------------------------------

    private static string Cell(string text) => text.Replace("|", "\\|", StringComparison.Ordinal);

    private static string Code(string text) => text.Replace("|", "\\|", StringComparison.Ordinal).Replace("`", "'", StringComparison.Ordinal);

    private static bool IsVisible(MethodBase? method) => method is not null && (method.IsPublic || method.IsFamily || method.IsFamilyOrAssembly);

    private static bool IsInitOnly(MethodInfo setter) =>
        setter.ReturnParameter.GetRequiredCustomModifiers().Any(m => m.FullName == "System.Runtime.CompilerServices.IsExternalInit");

    private static bool IsRecord(Type type) =>
        type.GetMethod("<Clone>$") is not null
        || type.GetProperty("EqualityContract", DocIds.NonPublicInstance) is not null
        || (type.IsValueType && type.GetMethod("PrintMembers", DocIds.NonPublicInstance) is not null);

    private static bool IsRecordCopyConstructor(ConstructorInfo ctor)
    {
        var parameters = ctor.GetParameters();
        return parameters.Length == 1 && parameters[0].ParameterType == ctor.DeclaringType && IsRecord(ctor.DeclaringType);
    }

    private static bool IsOverride(MethodInfo method) => method.IsVirtual && method.GetBaseDefinition().DeclaringType != method.DeclaringType;

    private static string Access(MethodBase method) => method.IsFamily ? "protected " : "";

    private static string Kind(Type type)
    {
        if (type.IsInterface) return "interface";
        if (type.IsEnum) return type.IsDefined(typeof(FlagsAttribute)) ? "[Flags] enum" : "enum";
        var record = IsRecord(type);
        if (type.IsValueType) return (type.IsDefined(typeof(IsReadOnlyAttribute)) ? "readonly " : "") + (record ? "record struct" : "struct");
        if (type.IsAbstract && type.IsSealed) return "static class";
        return (type.IsSealed ? "sealed " : type.IsAbstract ? "abstract " : "") + (record ? "record" : "class");
    }

    private static string BaseList(Type type)
    {
        if (type.IsEnum) return "";
        var bases = new List<string>();
        if (type.BaseType is { } baseType && baseType != typeof(object) && baseType != typeof(ValueType)) bases.Add(TypeName(baseType, null));
        var inherited = type.BaseType?.GetInterfaces() ?? Type.EmptyTypes;
        bases.AddRange(type.GetInterfaces()
            .Where(i => !inherited.Contains(i))
            .Where(i => i.Namespace?.StartsWith("VirtualMarina", StringComparison.Ordinal) == true
                || i == typeof(IDisposable)
                || i == typeof(IAsyncDisposable)
                || i.Name.StartsWith("IDictionary", StringComparison.Ordinal)
                || i.Name.StartsWith("IReadOnlyDictionary", StringComparison.Ordinal))
            .Select(i => TypeName(i, null)));
        return bases.Count > 0 ? " : " + string.Join(", ", bases.Distinct()) : "";
    }

    private static string DisplayTypeName(Type type)
    {
        if (!type.IsGenericType) return type.Name;
        var name = type.Name[..type.Name.IndexOf('`', StringComparison.Ordinal)];
        return $"{name}<{string.Join(", ", type.GetGenericArguments().Select(DisplayTypeName))}>";
    }

    private static string FormatValue(object? value, Type? type = null)
    {
        if (value is null or DBNull) return type is { IsValueType: true } && Nullable.GetUnderlyingType(type) is null ? "default" : "null";
        var underlying = type is null ? null : Nullable.GetUnderlyingType(type) ?? type;
        if (underlying is { IsEnum: true }) return $"{underlying.Name}.{Enum.GetName(underlying, value)}";
        return value switch
        {
            string s => $"\"{s}\"",
            bool b => b ? "true" : "false",
            float f => f.ToString(Invariant) + "f",
            double d => d.ToString(Invariant),
            _ => Convert.ToString(value, Invariant) ?? "",
        };
    }

    private static string TypeName(Type type, NullabilityInfo? info)
    {
        if (type.IsByRef) return TypeName(type.GetElementType()!, info?.ElementType ?? info);
        if (Nullable.GetUnderlyingType(type) is { } inner) return TypeName(inner, null) + "?";
        var nullable = info?.ReadState == NullabilityState.Nullable && !type.IsValueType ? "?" : "";

        if (type.IsArray) return TypeName(type.GetElementType()!, info?.ElementType) + "[]" + nullable;
        if (Aliases.TryGetValue(type, out var alias)) return alias + nullable;
        if (type.IsGenericParameter) return type.Name + nullable;
        if (!type.IsGenericType) return type.Name + nullable;

        var args = type.GetGenericArguments();
        var argNames = args.Select((a, i) => TypeName(a, info is not null && i < info.GenericTypeArguments.Length ? info.GenericTypeArguments[i] : null));
        var name = type.Name[..type.Name.IndexOf('`', StringComparison.Ordinal)];
        if (type.IsNested && type.DeclaringType is { } declaring) name = TypeName(declaring, null) + "." + name;
        return $"{name}<{string.Join(", ", argNames)}>{nullable}";
    }
}
