// Generates a Markdown API reference from the public surface of the VirtualMarina assemblies and their XML docs.
using System.Reflection;
using System.Runtime.CompilerServices;

namespace VirtualMarina.Docs.ApiDocGen;

internal static class Program
{
    private static async Task<int> Main(string[] args)
    {
        // With no argument the reference is regenerated in place, wherever the tool is run from.
        var output = args.Length > 0 ? args[0] : Path.Combine(RepositoryRoot(), "Docs", "11-api-reference.md");

        Assembly[] assemblies =
        [
            typeof(VirtualMarina.Core.Api.IMarinaVisualizer).Assembly,
            typeof(VirtualMarina.Rendering.OpenGL.OpenGlSceneRenderer).Assembly,
            typeof(VirtualMarina.WinForms.MarinaViewControl).Assembly,
            typeof(VirtualMarina.Blazor.MarinaView).Assembly,
        ];

        var docs = XmlDocumentation.Load(assemblies);

        var types = assemblies
            .SelectMany(a => a.GetExportedTypes())
            .Where(t => !t.IsDefined(typeof(CompilerGeneratedAttribute)))
            .Where(t => t.Name != "_Imports") // generated by the Razor SDK
            .OrderBy(t => t.Namespace, StringComparer.Ordinal)
            .ThenBy(t => t.Name, StringComparer.Ordinal)
            .ToList();

        var markdown = new ApiReferenceWriter(docs).Write(types);
        await File.WriteAllTextAsync(output, markdown.Replace("\r\n", "\n", StringComparison.Ordinal)).ConfigureAwait(false);
        await Console.Out.WriteLineAsync($"Wrote {types.Count} types to {Path.GetFullPath(output)}").ConfigureAwait(false);
        return 0;
    }

    /// <summary>The directory holding VirtualMarina.sln, found by walking up from the tool's own build output.</summary>
    private static string RepositoryRoot()
    {
        for (var directory = new DirectoryInfo(AppContext.BaseDirectory); directory is not null; directory = directory.Parent)
        {
            if (File.Exists(Path.Combine(directory.FullName, "VirtualMarina.sln"))) return directory.FullName;
        }

        throw new InvalidOperationException("No VirtualMarina.sln above the tool's build output; pass the output path as the argument.");
    }
}
