// Generates a Markdown API reference from the public surface of the VirtualMarina assemblies and their XML docs.
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Text;
using System.Text.RegularExpressions;
using System.Xml.Linq;

var output = args.Length > 0 ? args[0] : "11-api-reference.md";

var assemblies = new[]
{
    typeof(VirtualMarina.Core.Api.IMarinaVisualizer).Assembly,
    typeof(VirtualMarina.Rendering.OpenGL.OpenGlSceneRenderer).Assembly,
    typeof(VirtualMarina.WinForms.MarinaViewControl).Assembly,
    typeof(VirtualMarina.Blazor.MarinaView).Assembly,
};

var docs = new Dictionary<string, XElement>(StringComparer.Ordinal);
foreach (var assembly in assemblies)
{
    var xmlPath = Path.ChangeExtension(assembly.Location, ".xml");
    if (!File.Exists(xmlPath)) throw new FileNotFoundException("XML documentation not found; build the libraries first.", xmlPath);
    foreach (var member in XDocument.Load(xmlPath, LoadOptions.PreserveWhitespace).Descendants("member"))
    {
        docs[(string)member.Attribute("name")!] = member;
    }
}

var nullability = new NullabilityInfoContext();
var sb = new StringBuilder();
sb.AppendLine("# API reference");
sb.AppendLine();
sb.AppendLine("Every public type and member of the VirtualMarina libraries, with the summary from its XML documentation.");
sb.AppendLine("Generated by `Docs/tools/ApiDocGen` (`dotnet run --project Docs/tools/ApiDocGen -- Docs/11-api-reference.md`); do not edit by hand.");
sb.AppendLine("Guides with examples are listed in the [documentation index](README.md).");
sb.AppendLine();

var types = assemblies
    .SelectMany(a => a.GetExportedTypes())
    .Where(t => !t.IsDefined(typeof(CompilerGeneratedAttribute)))
    .Where(t => t.Name != "_Imports") // generated by the Razor SDK
    .OrderBy(t => t.Namespace, StringComparer.Ordinal)
    .ThenBy(t => t.Name, StringComparer.Ordinal)
    .ToList();

// Table of contents
foreach (var group in types.GroupBy(t => t.Namespace))
{
    sb.AppendLine($"- **{group.Key}**: " + string.Join(", ", group.Select(t => $"[{DisplayTypeName(t)}](#{Anchor(t)})")));
}

sb.AppendLine();

foreach (var group in types.GroupBy(t => t.Namespace))
{
    sb.AppendLine($"## {group.Key}");
    sb.AppendLine();

    foreach (var type in group)
    {
        sb.AppendLine($"<a id=\"{Anchor(type)}\"></a>");
        sb.AppendLine($"### {DisplayTypeName(type)}");
        sb.AppendLine();
        sb.AppendLine($"`{Kind(type)} {DisplayTypeName(type)}{BaseList(type)}`");
        sb.AppendLine();
        var typeDoc = Doc("T:" + TypeId(type));
        if (typeDoc.Summary.Length > 0) sb.AppendLine(typeDoc.Summary).AppendLine();
        if (typeDoc.Remarks.Length > 0) sb.AppendLine(typeDoc.Remarks).AppendLine();

        if (type.IsEnum)
        {
            sb.AppendLine("| Value | Description |");
            sb.AppendLine("|---|---|");
            foreach (var field in type.GetFields(BindingFlags.Public | BindingFlags.Static))
            {
                var value = Convert.ToInt64(field.GetRawConstantValue());
                sb.AppendLine($"| `{field.Name}` = {value} | {Cell(Doc("F:" + TypeId(type) + "." + field.Name).Summary)} |");
            }

            sb.AppendLine();
            continue;
        }

        var rows = new List<(string Signature, string Summary)>();
        const BindingFlags flags = BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.Static | BindingFlags.DeclaredOnly;

        foreach (var ctor in type.GetConstructors(flags).Where(IsVisible).Where(c => !IsRecordCopyConstructor(c)))
        {
            var summary = Doc("M:" + TypeId(type) + ".#ctor" + ParameterIds(ctor)).Summary;
            if (summary.Length == 0)
            {
                summary = ctor.GetParameters().Length == 0
                    ? "Creates an instance with default values."
                    : IsRecord(type) ? "Positional constructor; the parameters are described on the properties below." : "";
            }

            rows.Add(($"{Access(ctor)}{DisplayTypeName(type).Split('<')[0]}({Parameters(ctor)})", summary));
        }

        foreach (var field in type.GetFields(flags).Where(f => f.IsPublic || f.IsFamily).Where(f => !f.IsSpecialName))
        {
            var modifier = field.IsLiteral ? "const " : field.IsStatic ? "static readonly " : "";
            var constant = field.IsLiteral ? $" = {FormatValue(field.GetRawConstantValue())}" : "";
            rows.Add(($"{modifier}{TypeName(field.FieldType, nullability.Create(field))} {field.Name}{constant}", Doc("F:" + TypeId(type) + "." + field.Name).Summary));
        }

        foreach (var property in type.GetProperties(flags).Where(p => IsVisible(p.GetMethod) || IsVisible(p.SetMethod)))
        {
            if (property.Name == "EqualityContract") continue;
            var accessors = new List<string>();
            if (IsVisible(property.GetMethod)) accessors.Add("get;");
            if (IsVisible(property.SetMethod)) accessors.Add(IsInitOnly(property.SetMethod!) ? "init;" : "set;");
            var isStatic = (property.GetMethod ?? property.SetMethod)!.IsStatic ? "static " : "";
            var indexParameters = property.GetIndexParameters();
            var name = indexParameters.Length > 0 ? $"this[{string.Join(", ", indexParameters.Select(p => $"{TypeName(p.ParameterType, nullability.Create(p))} {p.Name}"))}]" : property.Name;
            var id = "P:" + TypeId(type) + "." + property.Name + (indexParameters.Length > 0 ? "(" + string.Join(",", indexParameters.Select(p => TypeIdOf(p.ParameterType))) + ")" : "");
            rows.Add(($"{isStatic}{TypeName(property.PropertyType, nullability.Create(property))} {name} {{ {string.Join(" ", accessors)} }}", Doc(id).Summary));
        }

        foreach (var ev in type.GetEvents(flags).Where(e => IsVisible(e.AddMethod)))
        {
            rows.Add(($"event {TypeName(ev.EventHandlerType!, nullability.Create(ev))} {ev.Name}", Doc("E:" + TypeId(type) + "." + ev.Name).Summary));
        }

        var hiddenMethods = new HashSet<string> { "Equals", "GetHashCode", "ToString", "Deconstruct", "PrintMembers", "<Clone>$" };
        if (typeof(Microsoft.AspNetCore.Components.ComponentBase).IsAssignableFrom(type)) hiddenMethods.Add("BuildRenderTree"); // Razor-generated
        foreach (var method in type.GetMethods(flags).Where(IsVisible).Where(m => !m.IsSpecialName).OrderBy(m => m.Name, StringComparer.Ordinal))
        {
            if (hiddenMethods.Contains(method.Name) && (IsRecord(type) || method.Name == "BuildRenderTree")) continue;
            if (method.Name is "Equals" or "GetHashCode" && method.DeclaringType!.IsValueType) continue;
            var genericArity = method.IsGenericMethodDefinition ? "``" + method.GetGenericArguments().Length : "";
            var id = "M:" + TypeId(type) + "." + method.Name + genericArity + ParameterIds(method);
            var generic = method.IsGenericMethodDefinition ? "<" + string.Join(", ", method.GetGenericArguments().Select(a => a.Name)) + ">" : "";
            var modifiers = (method.IsStatic ? "static " : "") + (method.IsFamily ? "protected " : "") + (IsOverride(method) ? "override " : "");
            var returnType = TypeName(method.ReturnType, nullability.Create(method.ReturnParameter));
            rows.Add(($"{modifiers}{returnType} {method.Name}{generic}({Parameters(method)})", Doc(id).Summary));
        }

        if (rows.Count > 0)
        {
            sb.AppendLine("| Member | Description |");
            sb.AppendLine("|---|---|");
            foreach (var (signature, summary) in rows) sb.AppendLine($"| `{Code(signature)}` | {Cell(summary)} |");
            sb.AppendLine();
        }
    }
}

File.WriteAllText(output, sb.ToString().Replace("\r\n", "\n"));
Console.WriteLine($"Wrote {types.Count} types to {Path.GetFullPath(output)}");

// ---- Helpers -------------------------------------------------------------------------------------

(string Summary, string Remarks) Doc(string id)
{
    if (!docs.TryGetValue(id, out var element)) return ("", "");
    if (element.Element("inheritdoc") is { } inherit && element.Element("summary") is null)
    {
        return (string?)inherit.Attribute("cref") is { } cref && cref != id ? Doc(cref) : ("*(See the interface member.)*", "");
    }

    return (Flatten(element.Element("summary")), Flatten(element.Element("remarks")));
}

static string Flatten(XElement? element)
{
    if (element is null) return "";
    var text = new StringBuilder();
    foreach (var node in element.Nodes()) Append(node, text);
    return Regex.Replace(text.ToString(), @"\s+", " ").Trim();

    static void Append(XNode node, StringBuilder text)
    {
        switch (node)
        {
            case XText t:
                text.Append(t.Value);
                break;
            case XElement e when e.Name == "see" || e.Name == "seealso":
                var cref = (string?)e.Attribute("cref") ?? (string?)e.Attribute("langword") ?? "";
                text.Append('`').Append(ShortCref(cref)).Append('`');
                break;
            case XElement e when e.Name == "paramref" || e.Name == "typeparamref":
                text.Append('`').Append((string?)e.Attribute("name")).Append('`');
                break;
            case XElement e when e.Name == "c":
                text.Append('`').Append(e.Value).Append('`');
                break;
            case XElement e when e.Name == "code":
                break; // examples are in the guides and IntelliSense
            case XElement e when e.Name == "para":
                foreach (var child in e.Nodes()) Append(child, text);
                text.Append(' ');
                break;
            case XElement e:
                foreach (var child in e.Nodes()) Append(child, text);
                break;
        }
    }
}

static string ShortCref(string cref)
{
    var withoutPrefix = cref.Length > 2 && cref[1] == ':' ? cref[2..] : cref;
    var name = withoutPrefix.Split('(')[0];
    var parts = name.Split('.');
    var shortName = cref.StartsWith("T:") ? parts[^1] : parts.Length >= 2 ? parts[^2] + "." + parts[^1] : parts[^1];
    return Regex.Replace(shortName.Replace("#ctor", "ctor"), "`+\\d+", "");
}

static string Cell(string text) => text.Replace("|", "\\|");

static string Code(string text) => text.Replace("|", "\\|").Replace("`", "'");

static string Anchor(Type type) => DisplayTypeName(type).ToLowerInvariant().Replace("<", "").Replace(">", "").Replace(".", "-").Replace(", ", "-");

static bool IsVisible(MethodBase? method) => method is not null && (method.IsPublic || method.IsFamily || method.IsFamilyOrAssembly);

static bool IsInitOnly(MethodInfo setter) =>
    setter.ReturnParameter.GetRequiredCustomModifiers().Any(m => m.FullName == "System.Runtime.CompilerServices.IsExternalInit");

static bool IsRecord(Type type) => type.GetMethod("<Clone>$") is not null || type.GetProperty("EqualityContract", BindingFlags.NonPublic | BindingFlags.Instance) is not null
    || (type.IsValueType && type.GetMethod("PrintMembers", BindingFlags.NonPublic | BindingFlags.Instance) is not null);

static bool IsRecordCopyConstructor(ConstructorInfo ctor)
{
    var parameters = ctor.GetParameters();
    return parameters.Length == 1 && parameters[0].ParameterType == ctor.DeclaringType && IsRecord(ctor.DeclaringType!);
}

static bool IsOverride(MethodInfo method) => method.IsVirtual && method.GetBaseDefinition().DeclaringType != method.DeclaringType;

static string Access(MethodBase method) => method.IsFamily ? "protected " : "";

static string Kind(Type type)
{
    if (type.IsInterface) return "interface";
    if (type.IsEnum) return type.IsDefined(typeof(FlagsAttribute)) ? "[Flags] enum" : "enum";
    var record = IsRecord(type);
    if (type.IsValueType) return (type.IsDefined(typeof(IsReadOnlyAttribute)) ? "readonly " : "") + (record ? "record struct" : "struct");
    if (type.IsAbstract && type.IsSealed) return "static class";
    return (type.IsSealed ? "sealed " : type.IsAbstract ? "abstract " : "") + (record ? "record" : "class");
}

static string BaseList(Type type)
{
    if (type.IsEnum) return "";
    var bases = new List<string>();
    if (type.BaseType is { } baseType && baseType != typeof(object) && baseType != typeof(ValueType)) bases.Add(TypeName(baseType, null));
    var inherited = type.BaseType?.GetInterfaces() ?? Type.EmptyTypes;
    bases.AddRange(type.GetInterfaces()
        .Where(i => !inherited.Contains(i))
        .Where(i => i.Namespace?.StartsWith("VirtualMarina") == true || i == typeof(IDisposable) || i == typeof(IAsyncDisposable) || i.Name.StartsWith("IDictionary") || i.Name.StartsWith("IReadOnlyDictionary"))
        .Select(i => TypeName(i, null)));
    return bases.Count > 0 ? " : " + string.Join(", ", bases.Distinct()) : "";
}

static string DisplayTypeName(Type type)
{
    if (!type.IsGenericType) return type.Name;
    var name = type.Name[..type.Name.IndexOf('`')];
    return $"{name}<{string.Join(", ", type.GetGenericArguments().Select(DisplayTypeName))}>";
}

string Parameters(MethodBase method) => string.Join(", ", method.GetParameters().Select(p =>
{
    var prefix = p.IsOut ? "out " : p.ParameterType.IsByRef ? "ref " : p.IsDefined(typeof(ParamArrayAttribute)) ? "params " : "";
    var type = TypeName(p.ParameterType.IsByRef ? p.ParameterType.GetElementType()! : p.ParameterType, nullability.Create(p));
    var defaultValue = p.HasDefaultValue ? " = " + FormatValue(p.RawDefaultValue, p.ParameterType) : "";
    return $"{prefix}{type} {p.Name}{defaultValue}";
}));

static string FormatValue(object? value, Type? type = null)
{
    if (value is null || value is DBNull) return type is { IsValueType: true } && Nullable.GetUnderlyingType(type) is null ? "default" : "null";
    var underlying = type is null ? null : Nullable.GetUnderlyingType(type) ?? type;
    if (underlying is { IsEnum: true }) return $"{underlying.Name}.{Enum.GetName(underlying, value)}";
    return value switch
    {
        string s => $"\"{s}\"",
        bool b => b ? "true" : "false",
        float f => f.ToString(System.Globalization.CultureInfo.InvariantCulture) + "f",
        double d => d.ToString(System.Globalization.CultureInfo.InvariantCulture),
        _ => Convert.ToString(value, System.Globalization.CultureInfo.InvariantCulture) ?? "",
    };
}

static string TypeName(Type type, NullabilityInfo? info)
{
    if (type.IsByRef) return TypeName(type.GetElementType()!, info?.ElementType ?? info);
    if (Nullable.GetUnderlyingType(type) is { } inner) return TypeName(inner, null) + "?";
    var nullable = info?.ReadState == NullabilityState.Nullable && !type.IsValueType ? "?" : "";

    if (type.IsArray) return TypeName(type.GetElementType()!, info?.ElementType) + "[]" + nullable;
    if (Aliases.TryGetValue(type, out var alias)) return alias + nullable;
    if (type.IsGenericParameter) return type.Name + nullable;
    if (!type.IsGenericType) return type.Name + nullable;

    var args = type.GetGenericArguments();
    var argNames = args.Select((a, i) => TypeName(a, info is not null && i < info.GenericTypeArguments.Length ? info.GenericTypeArguments[i] : null));
    var name = type.Name[..type.Name.IndexOf('`')];
    if (type.IsNested && type.DeclaringType is { } declaring) name = TypeName(declaring, null) + "." + name;
    return $"{name}<{string.Join(", ", argNames)}>{nullable}";
}

// ---- XML documentation ids ----------------------------------------------------------------------

static string TypeId(Type type) => (type.FullName ?? type.Name).Replace('+', '.');

static string ParameterIds(MethodBase method)
{
    var parameters = method.GetParameters();
    return parameters.Length == 0 ? "" : "(" + string.Join(",", parameters.Select(p => TypeIdOf(p.ParameterType))) + ")";
}

static string TypeIdOf(Type type)
{
    if (type.IsByRef) return TypeIdOf(type.GetElementType()!) + "@";
    if (type.IsArray) return TypeIdOf(type.GetElementType()!) + "[" + new string(',', type.GetArrayRank() - 1) + "]";
    if (type.IsGenericParameter) return type.DeclaringMethod is not null ? "``" + type.GenericParameterPosition : "`" + type.GenericParameterPosition;
    if (type.IsGenericType)
    {
        var definition = type.GetGenericTypeDefinition();
        var baseName = (definition.FullName ?? definition.Name).Replace('+', '.');
        baseName = baseName[..baseName.IndexOf('`')];
        return baseName + "{" + string.Join(",", type.GetGenericArguments().Select(TypeIdOf)) + "}";
    }

    return (type.FullName ?? type.Name).Replace('+', '.');
}

partial class Program
{
    private static readonly Dictionary<Type, string> Aliases = new()
    {
        [typeof(void)] = "void", [typeof(bool)] = "bool", [typeof(byte)] = "byte", [typeof(int)] = "int", [typeof(uint)] = "uint",
        [typeof(long)] = "long", [typeof(float)] = "float", [typeof(double)] = "double", [typeof(string)] = "string",
        [typeof(object)] = "object", [typeof(char)] = "char", [typeof(decimal)] = "decimal",
    };
}
